services:
  accounting_db:
    container_name: accounting_db 
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - accounting_db:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"

volumes:
  accounting_db: